name: ci-pipeline-maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and test
        run: mvn -B verify pitest:mutationCoverage
      - name: Save repository name
        run: echo "REPOSITORY_NAME=$(echo '${{github.repository}}'|awk-F '/''{print $2}')">>$GITHUB_ENV
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.REPOSITORY_NAME}}-reports
          path: |
            target/site/jacoco/
            target/pit-reports/
